# Generated by Django 5.0 on 2023-12-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bazaar', '0004_remove_comment_user_comment_email_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
